"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
require("antd/dist/antd.less");
/* @remove-on-es-build-begin */
// this file is not used if use https://github.com/ant-design/babel-plugin-import
var ENV = process.env.NODE_ENV;
if (ENV !== 'production' &&
    ENV !== 'test' &&
    typeof console !== 'undefined' &&
    console.warn && // eslint-disable-line no-console
    typeof window !== 'undefined') {
    // eslint-disable-next-line no-console
    console.warn('你正在全局引用' + '请使用 https://www.npmjs.com/package/babel-plugin-import 按需加载.');
}
/* @remove-on-es-build-end */
var affix_1 = require("./affix");
Object.defineProperty(exports, "Affix", { enumerable: true, get: function () { return affix_1.default; } });
var anchor_1 = require("./anchor");
Object.defineProperty(exports, "Anchor", { enumerable: true, get: function () { return anchor_1.default; } });
var auto_complete_1 = require("./auto-complete");
Object.defineProperty(exports, "AutoComplete", { enumerable: true, get: function () { return auto_complete_1.default; } });
var alert_1 = require("./alert");
Object.defineProperty(exports, "Alert", { enumerable: true, get: function () { return alert_1.default; } });
var avatar_1 = require("./avatar");
Object.defineProperty(exports, "Avatar", { enumerable: true, get: function () { return avatar_1.default; } });
var back_top_1 = require("./back-top");
Object.defineProperty(exports, "BackTop", { enumerable: true, get: function () { return back_top_1.default; } });
var badge_1 = require("./badge");
Object.defineProperty(exports, "Badge", { enumerable: true, get: function () { return badge_1.default; } });
var breadcrumb_1 = require("./breadcrumb");
Object.defineProperty(exports, "Breadcrumb", { enumerable: true, get: function () { return breadcrumb_1.default; } });
var button_1 = require("./button");
Object.defineProperty(exports, "Button", { enumerable: true, get: function () { return button_1.default; } });
var calendar_1 = require("./calendar");
Object.defineProperty(exports, "Calendar", { enumerable: true, get: function () { return calendar_1.default; } });
var card_1 = require("./card");
Object.defineProperty(exports, "Card", { enumerable: true, get: function () { return card_1.default; } });
var collapse_1 = require("./collapse");
Object.defineProperty(exports, "Collapse", { enumerable: true, get: function () { return collapse_1.default; } });
var carousel_1 = require("./carousel");
Object.defineProperty(exports, "Carousel", { enumerable: true, get: function () { return carousel_1.default; } });
var cascader_1 = require("./cascader");
Object.defineProperty(exports, "Cascader", { enumerable: true, get: function () { return cascader_1.default; } });
var checkbox_1 = require("./checkbox");
Object.defineProperty(exports, "Checkbox", { enumerable: true, get: function () { return checkbox_1.default; } });
var col_1 = require("./col");
Object.defineProperty(exports, "Col", { enumerable: true, get: function () { return col_1.default; } });
var comment_1 = require("./comment");
Object.defineProperty(exports, "Comment", { enumerable: true, get: function () { return comment_1.default; } });
var config_provider_1 = require("./config-provider");
Object.defineProperty(exports, "ConfigProvider", { enumerable: true, get: function () { return config_provider_1.default; } });
var date_picker_1 = require("./date-picker");
Object.defineProperty(exports, "DatePicker", { enumerable: true, get: function () { return date_picker_1.default; } });
var descriptions_1 = require("./descriptions");
Object.defineProperty(exports, "Descriptions", { enumerable: true, get: function () { return descriptions_1.default; } });
var divider_1 = require("./divider");
Object.defineProperty(exports, "Divider", { enumerable: true, get: function () { return divider_1.default; } });
var dropdown_1 = require("./dropdown");
Object.defineProperty(exports, "Dropdown", { enumerable: true, get: function () { return dropdown_1.default; } });
var drawer_1 = require("./drawer");
Object.defineProperty(exports, "Drawer", { enumerable: true, get: function () { return drawer_1.default; } });
var empty_1 = require("./empty");
Object.defineProperty(exports, "Empty", { enumerable: true, get: function () { return empty_1.default; } });
var form_1 = require("./form");
Object.defineProperty(exports, "Form", { enumerable: true, get: function () { return form_1.default; } });
var grid_1 = require("./grid");
Object.defineProperty(exports, "Grid", { enumerable: true, get: function () { return grid_1.default; } });
var input_1 = require("./input");
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return input_1.default; } });
var input_number_1 = require("./input-number");
Object.defineProperty(exports, "InputNumber", { enumerable: true, get: function () { return input_number_1.default; } });
var layout_1 = require("./layout");
Object.defineProperty(exports, "Layout", { enumerable: true, get: function () { return layout_1.default; } });
var list_1 = require("./list");
Object.defineProperty(exports, "List", { enumerable: true, get: function () { return list_1.default; } });
var message_1 = require("./message");
Object.defineProperty(exports, "message", { enumerable: true, get: function () { return message_1.default; } });
var menu_1 = require("./menu");
Object.defineProperty(exports, "Menu", { enumerable: true, get: function () { return menu_1.default; } });
var mentions_1 = require("./mentions");
Object.defineProperty(exports, "Mentions", { enumerable: true, get: function () { return mentions_1.default; } });
var modal_1 = require("./modal");
Object.defineProperty(exports, "Modal", { enumerable: true, get: function () { return modal_1.default; } });
var statistic_1 = require("./statistic");
Object.defineProperty(exports, "Statistic", { enumerable: true, get: function () { return statistic_1.default; } });
var notification_1 = require("./notification");
Object.defineProperty(exports, "notification", { enumerable: true, get: function () { return notification_1.default; } });
var page_header_1 = require("./page-header");
Object.defineProperty(exports, "PageHeader", { enumerable: true, get: function () { return page_header_1.default; } });
var pagination_1 = require("./pagination");
Object.defineProperty(exports, "Pagination", { enumerable: true, get: function () { return pagination_1.default; } });
var popconfirm_1 = require("./popconfirm");
Object.defineProperty(exports, "Popconfirm", { enumerable: true, get: function () { return popconfirm_1.default; } });
var popover_1 = require("./popover");
Object.defineProperty(exports, "Popover", { enumerable: true, get: function () { return popover_1.default; } });
var progress_1 = require("./progress");
Object.defineProperty(exports, "Progress", { enumerable: true, get: function () { return progress_1.default; } });
var radio_1 = require("./radio");
Object.defineProperty(exports, "Radio", { enumerable: true, get: function () { return radio_1.default; } });
var rate_1 = require("./rate");
Object.defineProperty(exports, "Rate", { enumerable: true, get: function () { return rate_1.default; } });
var result_1 = require("./result");
Object.defineProperty(exports, "Result", { enumerable: true, get: function () { return result_1.default; } });
var row_1 = require("./row");
Object.defineProperty(exports, "Row", { enumerable: true, get: function () { return row_1.default; } });
var select_1 = require("./select");
Object.defineProperty(exports, "Select", { enumerable: true, get: function () { return select_1.default; } });
var skeleton_1 = require("./skeleton");
Object.defineProperty(exports, "Skeleton", { enumerable: true, get: function () { return skeleton_1.default; } });
var slider_1 = require("./slider");
Object.defineProperty(exports, "Slider", { enumerable: true, get: function () { return slider_1.default; } });
var space_1 = require("./space");
Object.defineProperty(exports, "Space", { enumerable: true, get: function () { return space_1.default; } });
var spin_1 = require("./spin");
Object.defineProperty(exports, "Spin", { enumerable: true, get: function () { return spin_1.default; } });
var steps_1 = require("./steps");
Object.defineProperty(exports, "Steps", { enumerable: true, get: function () { return steps_1.default; } });
var switch_1 = require("./switch");
Object.defineProperty(exports, "Switch", { enumerable: true, get: function () { return switch_1.default; } });
var table_1 = require("./table");
Object.defineProperty(exports, "Table", { enumerable: true, get: function () { return table_1.default; } });
var transfer_1 = require("./transfer");
Object.defineProperty(exports, "Transfer", { enumerable: true, get: function () { return transfer_1.default; } });
var tree_1 = require("./tree");
Object.defineProperty(exports, "Tree", { enumerable: true, get: function () { return tree_1.default; } });
var tree_select_1 = require("./tree-select");
Object.defineProperty(exports, "TreeSelect", { enumerable: true, get: function () { return tree_select_1.default; } });
var tabs_1 = require("./tabs");
Object.defineProperty(exports, "Tabs", { enumerable: true, get: function () { return tabs_1.default; } });
var tag_1 = require("./tag");
Object.defineProperty(exports, "Tag", { enumerable: true, get: function () { return tag_1.default; } });
var time_picker_1 = require("./time-picker");
Object.defineProperty(exports, "TimePicker", { enumerable: true, get: function () { return time_picker_1.default; } });
var timeline_1 = require("./timeline");
Object.defineProperty(exports, "Timeline", { enumerable: true, get: function () { return timeline_1.default; } });
var tooltip_1 = require("./tooltip");
Object.defineProperty(exports, "Tooltip", { enumerable: true, get: function () { return tooltip_1.default; } });
var typography_1 = require("./typography");
Object.defineProperty(exports, "Typography", { enumerable: true, get: function () { return typography_1.default; } });
var upload_1 = require("./upload");
Object.defineProperty(exports, "Upload", { enumerable: true, get: function () { return upload_1.default; } });
__exportStar(require("./icon"), exports);
//# sourceMappingURL=index.js.map